stages:
  - test


test_mg5creator:
  image: python:3.7-alpine
  script:
    - >
      ./scripts/mg5creator.py -P cards/process/charginos \
                              -r cards/run/default_LO.dat \
                              -p cards/param/Higgsino.slha \
                              -y cards/pythia/pythia8_card.dat \
                              -m MN1 150.0 \
                              -m MN2 155.0 \
                              -m MC1 155.0 \
                              -E 100000 \
                              -n 1000 \
                              -t test
