[base]
path = "{{PWD}}"
output = "output"
database = "/data/users/{{USER}}/SUSY"
process_path = "cards/process/"
param_path = "cards/param/"
run_path = "cards/run/"
pythia_path = "cards/pythia/"
delphes_path = "cards/delphes/"

[madgraph]
skip = false
params = "Higgsino"
dM = 1
ecms = 13000
cores = 20
nevents = 10000
seed = 0
version = "madgraph"
batch = false
paramcard = "{{base['param_path']}}{{madgraph['params']}}.slha"

[madgraph.masses]
MN1 = 150
MC1 = 100

[madgraph.run]
card = "{{base['run_path']}}default_LO.dat"

[madgraph.run.options]
mmjj = 500
mmjjmax = -1
deltaeta = 3.0
ktdurham = -1
xqcut = -1
ptj = 20
ptj1min = 0

[madgraph.proc]
name = "VBFSUSY_EWKQCD"
card = "{{base['process_path']}}{{madgraph['proc']['name']}}"

[madspin]
skip = true
card = ''

[pythia]
skip = false
card = "{{base['pythia_path']}}pythia8_card_dipoleRecoil.dat"
additional_opts = ""

[delphes]
skip = false
additional_opts = ""
card = "delphes_card_ATLAS.tcl"
version = "delphes"

[analysis]
script = "SimpleAna.py"
XSoverride = -1
kfactor = -1

[simpleanalysis]
skip = false
additional_opts = ""
name = "EwkCompressed2018"

[pyhf]
skip = true
likelihood = "Higgsino_2L_bkgonly"
