[base]
path = "{{PWD}}"
database = "/data/users/{{USER}}/SUSY"
process_path = "cards/process/"
param_path = "cards/param/"
pythia_path = "cards/pythia/"
delphes_path = "cards/delphes/"

[madgraph]
skip = false
proc = "VBFSUSY_EWKQCD"
params = "Higgsino"
dM = 1
mass = 150
mmjj = 500
mmjjmax = -1
deltaeta = 3.0
ecms = 13000
cores = 20
ktdurham = -1
xqcut = -1
nevents = 10000
seed = 0
ptj = 20
ptj1min = 0
additional_opts = ""
version = "madgraph"
runcard = "default_LO.dat"
proccard = "{{base['process_path']}}{{madgraph['proc']}}"
paramcard = "{{base['param_path']}}{{madgraph['params']}}.slha"

[pythia]
skip = false
card = "{{base['pythia_path']}}pythia8_card_dipoleRecoil.dat"
additional_opts = ""

[delphes]
skip = false
additional_opts = ""
card = "delphes_card_ATLAS.tcl"

[analysis]
script = "SimpleAna.py"
XSoverride = -1
kfactor = -1

[simpleanalysis]
skip = false
additional_opts = ""
name = "EwkCompressed2018"

[pyhf]
skip = true
likelihood = "Higgsino_2L_bkgonly"
