[base]
path = "{{PWD}}"
output = "output"
data_path = "{{MAPYDE_DATA}}"
cards_path = "{{MAPYDE_CARDS}}"
scripts_path = "{{MAPYDE_SCRIPTS}}"
process_path = "{{MAPYDE_CARDS}}/process/"
param_path = "{{MAPYDE_CARDS}}/param/"
run_path = "{{MAPYDE_CARDS}}/run/"
pythia_path = "{{MAPYDE_CARDS}}/pythia/"
delphes_path = "{{MAPYDE_CARDS}}/delphes/"
madspin_path = "{{MAPYDE_CARDS}}/madspin/"

[madgraph]
skip = false
params = "Higgsino"
ecms = 13000
cores = 20
nevents = 10000
seed = 0
version = "madgraph"
batch = false
paramcard = "{{madgraph['params']}}.slha"

[madgraph.masses]
MN1 = 150
MC1 = 100

[madgraph.run]
card = "default_LO.dat"

[madgraph.run.options]
mmjj = 500
mmjjmax = -1
deltaeta = 3.0
ktdurham = -1
xqcut = -1
ptj = 20
ptj1min = 0

[madgraph.proc]
name = "VBFSUSY_EWKQCD"
card = "{{madgraph['proc']['name']}}"

[madspin]
skip = true
card = ''

[pythia]
skip = false
card = "pythia8_card_dipoleRecoil.dat"
additional_opts = ""

[delphes]
skip = false
additional_opts = ""
card = "delphes_card_ATLAS.tcl"
version = "delphes"

[analysis]
script = "SimpleAna.py"
XSoverride = -1
kfactor = -1
output = "SimpleAna.root"
lumi = 1000

[simpleanalysis]
skip = false
additional_opts = ""
name = "EwkCompressed2018"

[pyhf]
skip = true
likelihood = "Higgsino_2L_bkgonly"
